apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: postgresql
  type: database

resources:
  - statefulset.yaml
  - service.yaml
  - serviceaccount.yaml

secretGenerator:
  - name: postgresql
    env: secrets.env

images:
  - name: postgres