---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: kube-system
  labels:
    app: kibana
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: 'docker/default'
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana-oss:7.1.0
        resources:
          # need more cpu upon initialization, therefore burstable class
          limits:
            cpu: 1
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_HOSTS
            value: 'https://vpc-ocp-test3-tdfdagjwlqebrrvxv7fzk6s464.eu-central-1.es.amazonaws.com/'
        ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /api/status
            port: ui
          initialDelaySeconds: 5
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/status
            port: ui
          initialDelaySeconds: 5
          timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  type: ClusterIP
  ports:
  - port: 5601
    targetPort: 5601
    name: ui
    protocol: TCP
  selector:
    app: kibana