apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: keycloak
  type: keycloak

resources:
  - statefulset.yaml
  - service.yaml
  - service-ping.yaml
  - serviceaccount.yaml

configMapGenerator:
  - name: keycloak
    env: config.env

secretGenerator:
  - name: keycloak
    env: secrets.env

images:
  - name: keycloak
    newName: quay.io/keycloak/keycloak
    newTag: latest 