apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  volumeClaimTemplates: []
  updateStrategy:
    type: RollingUpdate
  serviceName: keycloak
  template:
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: keycloak
        - secretRef:
            name: keycloak
        image: keycloak
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /auth/
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 3
        name: keycloak
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /auth/
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccount: keycloak
      serviceAccountName: keycloak
      terminationGracePeriodSeconds: 120