apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxysql
spec:
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    activeDeadlineSeconds: 300
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 180
      updatePeriodSeconds: 1
    type: Rolling
  template:
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: proxysql
        image: proxysql
        imagePullPolicy: IfNotPresent
        name: proxysql
        ports:
        - containerPort: 3306
          protocol: TCP
        - containerPort: 6033
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
