apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: proxysql
  type: database

resources:
  - deployment.yaml
  - service.yaml

secretGenerator:
  - name: proxysql
    env: secrets.env
