apiVersion: v1
kind: Service
metadata:
  name: proxysql
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
    name: sql
    protocol: TCP
  - port: 6033
    targetPort: 6033
    protocol: TCP
    name: sql2
