apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: 'aws://eu-central-1a/vol-00669cdf17038d730'
    fsType: xfs
  capacity: 
    storage: 300Gi
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
